# Generated by Django 2.2.4 on 2019-08-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='approved_remark',
            new_name='approved_comment',
        ),
        migrations.AlterField(
            model_name='remark',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.Post'),
        ),
    ]
